### ISSUE TITLE
DNS/DKIM Handling?

### ISSUE THREAD

**Issue by bronson** [mailcow/mailcow-dockerized-docs#34]
Hi, I'm a little confused by the docs.

The first feature described by the overview is "DKIM Key Management": https://mailcow.github.io/mailcow-dockerized-docs/#overview

But this page makes it look like DKIM (and all keys) are managed 100% manually: https://mailcow.github.io/mailcow-dockerized-docs/prerequesite-dns/#dkim-spf-and-dmarc

Is one or the other of these out of date?

**Comment by mkuron** [comment]
You create a DKIM key in the web UI (that's what the feature list calls "DKIM Key Management"). Though to actually be useful, these DKIM keys need to be published in DNS TXT records, and that is manual work as it depends on your domain hoster, meaning it cannot be automated.

**Comment by bronson** [comment]
I understand.  Are there any thoughts on adding DNS serving so SPF, DKIM, etc can be automatic?

Thanks very much for the answer.  Closing since this isn't an issue.

**Comment by mkuron** [comment]
Built-in DNS services have been requested at https://github.com/mailcow/mailcow-dockerized/issues/438 . I don't consider that a good idea because it would make it difficult to DNSSEC-sign your domain as many domain providers do not let you create the DS records needed to publish your public key as a glue record in the parent zone.
